### ISSUE TITLE
Error on Bridge.before

### ISSUE THREAD

**Issue by sergiogarfe** [strongloop/strong-pubsub-bridge#2]
Hello,

I'm trying use a bridge.before('subscribe'..) and deny the subscribe. If I put ctx.authorized = false on this bridge.before, its throw the next error: 

``` javascript
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Invalid qos vector
    at suback (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/mqtt-packet/generate.js:402:11)
    at generate (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/mqtt-packet/generate.js:25:14)
    at DestroyableTransform.process [as _transform] (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/lib/generateStream.js:13:16)
    at DestroyableTransform.Transform._read (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Connection.callWrite3Args [as _callWrite] (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/reduplexer/index.js:50:25)
    at Connection.write [as _write] (/Users/sergio.garcia/Desktop/Desarrollo/backend/loopback/example-global/node_modules/strong-pubsub-connection-mqtt/node_modules/mqtt-connection/node_modules/reduplexer/index.js:147:17)
```

My code is: 

``` javascript
        bridge.before('subscribe',function (ctx, next) {
            ctx.authorized = false;
            next();
        });
```

**Comment by ritch** [comment]
@sergiogarfe can you shed some light on the rest of your setup?

**Comment by sergiogarfe** [comment]
Hello @ritch,
Of course, this is my server:

``` javascript
var path = require('path');
var duplex = require('duplex');
var Client = require('strong-pubsub');
var Bridge = require('strong-pubsub-bridge');
var Adapter = require('strong-pubsub-mqtt');
var Connection = require('strong-pubsub-connection-mqtt');
var http = require('http');
var net = require('net');
var browserify = require('browserify');
var express = require('express');
var Primus = require('primus');

var HTTP_PORT = process.env.HTTP_PORT || 3000;
var TCP_PORT = process.env.TCP_PORT || 4000;
var MOSQUITTO_PORT = process.env.MOSQUITTO_PORT || 6000;



  var app = express();

  app.use(express.static(path.join(__dirname, 'public')));

  var httpServer = http.createServer(app);
  // var tcpServer = net.createServer();
  var primus = new Primus(httpServer, {
    transformer: 'engine.io',
    parser: 'binary'
  });

  primus.on('connection', function(spark) {

    var bridge = new Bridge(
      new Connection(spark),
      new Client({port: MOSQUITTO_PORT}, Adapter)
    );

    bridge.connect();

    bridge.before('subscribe',function (ctx, next) {

        ctx.authorized = false;

          next();
      });

  });

  httpServer.listen(HTTP_PORT, function(err) {
    console.log(err || 'HTTP server listening at port ' + HTTP_PORT);
  });

```

and this, my client:

``` javascript
var PORT = process.env.PORT;
var TOPIC = process.env.TOPIC;
var readline = require('readline');
var Client = require('strong-pubsub');
var Adapter = require('strong-pubsub-mqtt');
var transporter = require('strong-pubsub-primus');
var Request = require('request');

var client = new Client({port: PORT,mqtt:mqttOptions}, Adapter, transporter);


client.subscribe(TOPIC,{},function (err) {
    if ( !err ) {
        console.log("ok!");

    } else {
        console.log("cb subscribe err: "+err);
    }
});
```

**Comment by muneebs** [comment]
I get the same error. Any suggestions?

**Comment by michaelfreund** [comment]
having the same issue. after applying 9d7054f (859d8cb) everything seems to work. @ritch any chance to review/verify this?

**Comment by lazydino** [comment]
Hooks won't work without this fix, please review/verify the issue.
